<?php
namespace Database\Seeders;
use App\Models\MenuItem;
use Illuminate\Database\Seeder;
class MenuItemSeeder extends Seeder {
    public function run(): void {
        if (MenuItem::count() > 0) return;
        $items = [
            ['id'=>'meal-001','name'=>'Grilled Chicken Breast','category'=>'protein','image'=>'https://picsum.photos/seed/meal1/400/300','calories'=>320,'protein'=>42,'carbs'=>8,'fat'=>12,'tags'=>['high-protein','gluten-free'],'description'=>'Lean grilled chicken with herbs','ingredients'=>['chicken breast','olive oil','garlic','rosemary'],'options'=>[]],
            ['id'=>'meal-002','name'=>'Salmon Fillet','category'=>'protein','image'=>'https://picsum.photos/seed/meal2/400/300','calories'=>380,'protein'=>38,'carbs'=>4,'fat'=>22,'tags'=>['omega-3','keto'],'description'=>'Atlantic salmon with lemon butter','ingredients'=>['salmon','lemon','butter','dill'],'options'=>[]],
            ['id'=>'meal-003','name'=>'Beef Steak','category'=>'protein','image'=>'https://picsum.photos/seed/meal3/400/300','calories'=>450,'protein'=>48,'carbs'=>2,'fat'=>26,'tags'=>['high-protein','keto'],'description'=>'Premium beef sirloin','ingredients'=>['sirloin','pepper','salt','butter'],'options'=>[]],
            ['id'=>'meal-004','name'=>'Chicken Shawarma Bowl','category'=>'main','image'=>'https://picsum.photos/seed/meal4/400/300','calories'=>520,'protein'=>35,'carbs'=>45,'fat'=>18,'tags'=>['middle-eastern','popular'],'description'=>'Classic shawarma with rice','ingredients'=>['chicken','rice','garlic sauce','pickles','tomato'],'options'=>[]],
            ['id'=>'meal-005','name'=>'Lamb Kofta','category'=>'main','image'=>'https://picsum.photos/seed/meal5/400/300','calories'=>480,'protein'=>32,'carbs'=>28,'fat'=>24,'tags'=>['arabic','grilled'],'description'=>'Spiced lamb kofta with flatbread','ingredients'=>['lamb mince','onion','parsley','cumin','flatbread'],'options'=>[]],
            ['id'=>'meal-006','name'=>'Quinoa Salad','category'=>'salad','image'=>'https://picsum.photos/seed/meal6/400/300','calories'=>290,'protein'=>12,'carbs'=>42,'fat'=>10,'tags'=>['vegan','healthy'],'description'=>'Fresh quinoa with roasted vegetables','ingredients'=>['quinoa','cucumber','tomato','olive oil','lemon'],'options'=>[]],
            ['id'=>'meal-007','name'=>'Caesar Salad','category'=>'salad','image'=>'https://picsum.photos/seed/meal7/400/300','calories'=>260,'protein'=>8,'carbs'=>18,'fat'=>16,'tags'=>['vegetarian','classic'],'description'=>'Romaine with caesar dressing','ingredients'=>['romaine','croutons','parmesan','caesar dressing'],'options'=>[]],
            ['id'=>'meal-008','name'=>'Brown Rice Bowl','category'=>'carbs','image'=>'https://picsum.photos/seed/meal8/400/300','calories'=>340,'protein'=>8,'carbs'=>68,'fat'=>4,'tags'=>['vegan','fiber-rich'],'description'=>'Steamed brown rice with vegetables','ingredients'=>['brown rice','broccoli','carrot','soy sauce'],'options'=>[]],
            ['id'=>'meal-009','name'=>'Oatmeal Bowl','category'=>'breakfast','image'=>'https://picsum.photos/seed/meal9/400/300','calories'=>280,'protein'=>10,'carbs'=>48,'fat'=>6,'tags'=>['breakfast','fiber-rich'],'description'=>'Rolled oats with fruits and honey','ingredients'=>['oats','banana','berries','honey','milk'],'options'=>[]],
            ['id'=>'meal-010','name'=>'Eggs Benedict','category'=>'breakfast','image'=>'https://picsum.photos/seed/meal10/400/300','calories'=>420,'protein'=>22,'carbs'=>28,'fat'=>24,'tags'=>['breakfast','classic'],'description'=>'Poached eggs with hollandaise','ingredients'=>['eggs','english muffin','ham','hollandaise'],'options'=>[]],
            ['id'=>'meal-011','name'=>'Lentil Soup','category'=>'soup','image'=>'https://picsum.photos/seed/meal11/400/300','calories'=>240,'protein'=>14,'carbs'=>36,'fat'=>4,'tags'=>['vegan','warm'],'description'=>'Red lentil soup with cumin','ingredients'=>['red lentils','onion','cumin','tomato','lemon'],'options'=>[]],
            ['id'=>'meal-012','name'=>'Chicken Broth','category'=>'soup','image'=>'https://picsum.photos/seed/meal12/400/300','calories'=>180,'protein'=>16,'carbs'=>8,'fat'=>6,'tags'=>['light','healthy'],'description'=>'Clear chicken broth with vegetables','ingredients'=>['chicken','carrot','celery','bay leaf'],'options'=>[]],
            ['id'=>'meal-013','name'=>'Hummus Plate','category'=>'snack','image'=>'https://picsum.photos/seed/meal13/400/300','calories'=>220,'protein'=>8,'carbs'=>24,'fat'=>10,'tags'=>['vegan','mediterranean'],'description'=>'Creamy hummus with pita','ingredients'=>['chickpeas','tahini','olive oil','pita'],'options'=>[]],
            ['id'=>'meal-014','name'=>'Mixed Nuts','category'=>'snack','image'=>'https://picsum.photos/seed/meal14/400/300','calories'=>180,'protein'=>6,'carbs'=>8,'fat'=>14,'tags'=>['keto','healthy-fat'],'description'=>'Premium mixed nuts blend','ingredients'=>['almonds','cashews','walnuts','pistachios'],'options'=>[]],
            ['id'=>'meal-015','name'=>'Grilled Vegetables','category'=>'side','image'=>'https://picsum.photos/seed/meal15/400/300','calories'=>140,'protein'=>4,'carbs'=>22,'fat'=>4,'tags'=>['vegan','low-calorie'],'description'=>'Seasonal grilled vegetables','ingredients'=>['zucchini','bell pepper','eggplant','olive oil'],'options'=>[]],
            ['id'=>'meal-016','name'=>'Sweet Potato Mash','category'=>'side','image'=>'https://picsum.photos/seed/meal16/400/300','calories'=>200,'protein'=>4,'carbs'=>44,'fat'=>2,'tags'=>['vegan','fiber-rich'],'description'=>'Creamy sweet potato mash','ingredients'=>['sweet potato','butter','cinnamon','salt'],'options'=>[]],
            ['id'=>'meal-017','name'=>'Greek Yogurt Parfait','category'=>'dessert','image'=>'https://picsum.photos/seed/meal17/400/300','calories'=>220,'protein'=>14,'carbs'=>28,'fat'=>4,'tags'=>['high-protein','probiotic'],'description'=>'Greek yogurt with granola and berries','ingredients'=>['greek yogurt','granola','strawberries','honey'],'options'=>[]],
        ];
        foreach ($items as $item) MenuItem::create($item);
    }
}
